" Tony Custom Vim
set nocompatible
filetype off

" We use Vundle manager
set rtp+=/home/common/vim/bundle/Vundle.vim

" Plugin defines here
call vundle#begin()
Plugin 'VundleVim/Vundle.vim'
Plugin 'tpope/vim-fugitive'
"Plugin 'git://git.wincent.com/command-t.git'
Plugin 'rstacruz/sparkup', {'rtp': 'vim/'}
Plugin 'itchyny/lightline.vim'
Plugin 'davidhalter/jedi-vim'
"Plugin 'terryma/vim-multiple-cursors'
Plugin 'preservim/nerdtree'
Plugin 'dense-analysis/ale'
Plugin 'airblade/vim-gitgutter'
"Plugin 'jiangmiao/auto-pairs'
"Plugin 'lervag/vimtex'
"Plugin 'sjl/badwolf'
"Plugin 'ctrlpvim/ctrlp.vim'
"Plugin 'bluz71/vim-nightfly-guicolors'
"Plugin 'godlygeek/tabular'
"Plugin 'plasticboy/vim-markdown'
Plugin 'trusktr/seti.vim'
call vundle#end()


filetype plugin indent on

" set Itchyny on
set laststatus=2

set completeopt-=preview




"let g:jedi#auto_initialization = 0
"let g:jedi#auto_vim_configuration = 0
let g:jedi#use_tabs_not_buffers = 1
let g:jedi#use_splits_not_buffers = "left"
let g:jedi#show_call_signatures = "0"
let g:jedi#popup_on_dot = 0


"set cursorcolumn
"set cursorline
