export TERM="screen-256color"
[[ $TMUX = "" ]] && export TERM="xterm-256color"

export PATH="/var/lib/flatpak/exports/share:/WORKSPACE/go/bin:/usr/local/bin:/usr/local/go/bin:/home/common/bin:/var/lib/snapd/snap/bin:/var/lib/flatpak/exports/share:/home/common/flutter/bin:/usr/local/cuda-12.2/bin:/home/common/helix:$PATH"
# If you come from bash you might have to change your $PATH.
# export PATH=$HOME/bin:/usr/local/bin:$PATH
# Path to your oh-my-zsh installation.
export ZSH="/home/common/oh-my-zsh"

# Set name of the theme to load --- if set to "random", it will
# load a random theme each time oh-my-zsh is loaded, in which case,
# to know which specific one was loaded, run: echo $RANDOM_THEME
# See https://github.com/ohmyzsh/ohmyzsh/wiki/Themes
ZSH_THEME="powerlevel10k/powerlevel10k"
[[ $TTY == *"tty"* ]] && ZSH_THEME="maran"
[[ "$TERM_PROGRAM" == "vscode" ]] && ZSH_THEME="maran"
[[ -n "$JUPYTER_SERVER_ROOT" ]] && ZSH_THEME="maran"

POWERLEVEL9K_MODE="nerdfont-complete"

POWERLEVEL9K_DISABLE_RPROMPT=true
POWERLEVEL9K_PROMPT_ON_NEWLINE=true
POWERLEVEL9K_ANACONDA_SHOW_PYTHON_VERSION=true
#POWERLEVEL9K_MULTILINE_LAST_PROMPT_PERFIX=""
#POWERLEVEL9K_MULTILINE_FIRST_PROMPT_PERFIX=""
#
POWERLEVEL9K_ANACONDA_LEFT_DELIMITER=""
POWERLEVEL9K_ANACONDA_RIGHT_DELIMITER=""
#POWERLEVEL9K_PYTHON_ICON=""
POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(os_icon anaconda battery user host load status dir vcs) 
#[[ $TMUX = "" ]] && POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(os_icon anaconda battery user host load status dir vcs) 
#POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(status root_indicator load  background_jobs history time)
#[[ $TMUX != "" ]] && POWERLEVEL9K_SHORTEN_DIR_LENGTH=1
#[[ $TMUX != "" ]] && POWERLEVEL9K_SHORTEN_STRATEGY=truncate_folders
#[[ $TMUX != "" ]] && POWERLEVEL9K_SHORTEN_DELIMITER=""

#POWERLEVEL9K_COLOR_SCHEME='light'


#POWERLEVEL9K_CUSTOM_FEDORA_ICON="echo "
#POWERLEVEL9K_CUSTOM_FEDORA_ICON_BACKGROUND=069
#POWERLEVEL9K_CUSTOM_FEDORA_ICON_FOREGROUND=015

#ZSH_TMUX_AUTOSTART=true
#ZSH_TMUX_AUTOSTART_ONCE=true
#ZSH_TMUX_AUTOCONNECT=true
#ZSH_TMUX_AUTOQUIT=true
#ZSH_TMUX_FIXTERM=true
# Set list of themes to pick from when loading at random
# Setting this variable when ZSH_THEME=random will cause zsh to load
# a theme from this variable instead of looking in ~/.oh-my-zsh/themes/
# If set to an empty array, this variable will have no effect.
# ZSH_THEME_RANDOM_CANDIDATES=( "robbyrussell" "agnoster" )

# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to use hyphen-insensitive completion.
# Case-sensitive completion must be off. _ and - will be interchangeable.
# HYPHEN_INSENSITIVE="true"

# Uncomment the following line to disable bi-weekly auto-update checks.
# DISABLE_AUTO_UPDATE="true"

# Uncomment the following line to automatically update without prompting.
# DISABLE_UPDATE_PROMPT="true"

# Uncomment the following line to change how often to auto-update (in days).
# export UPDATE_ZSH_DAYS=13

# Uncomment the following line if pasting URLs and other text is messed up.
# DISABLE_MAGIC_FUNCTIONS=true

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
# ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
# COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# You can set one of the optional three formats:
# "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# or set a custom format using the strftime function format specifications,
# see 'man strftime' for details.
# HIST_STAMPS="mm/dd/yyyy"

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder

# Which plugins would you like to load?
# Standard plugins can be found in ~/.oh-my-zsh/plugins/*
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(git tmux conda-zsh-completion kubectl-autocomplete zsh-autosuggestions zsh-syntax-highlighting)

source $ZSH/oh-my-zsh.sh

autoload -U compinit && compinit

alias yt-dlp="/usr/bin/yt-dlp -f mp4"
#alias vim="nvim"

alias setclip="xclip -selection clipboard"
alias getclip="xclip -selection clipboard -o"

if command -v lsd &> /dev/null 
then
  alias ls="lsd"
fi
alias l='/bin/ls --color'
alias la='ls -a'
alias lla='ls -la'
alias lt='ls --tree'
# User configuration

# export MANPATH="/usr/local/man:$MANPATH"

# You may need to manually set your language environment
# export LANG=en_US.UTF-8

# Preferred editor for local and remote sessions
# if [[ -n $SSH_CONNECTION ]]; then
#   export EDITOR='vim'
# else
#   export EDITOR='mvim'
# fi

# Compilation flags
# export ARCHFLAGS="-arch x86_64"

# Set personal aliases, overriding those provided by oh-my-zsh libs,
# plugins, and themes. Aliases can be placed here, though oh-my-zsh
# users are encouraged to define aliases within the ZSH_CUSTOM folder.
# For a full list of active aliases, run `alias`.
#
# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"
#

# Startup Script
source /home/common/install/zstartupscript.sh
if which helm >/dev/null; then
  source <(helm completion zsh)
fi

export GOPATH="/WORKSPACE/go"

export SASS=sassc
export SHELL=/bin/zsh

export XDG_DATA_HOME="/var/lib/flatpak/exports/share"
export XDG_DATA_DIRS="$XDG_DATA_DIRS:/var/lib/flatpak/exports/share"

# CUDA
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/cuda-12.2/lib64:/usr/local/lib:/home/tony/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib #:/home/common/miniconda3/envs/tf/lib

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

export PATH=~/.local/bin:$PATH

# Generated for envman. Do not edit.
[ -s "$HOME/.config/envman/load.sh" ] && source "$HOME/.config/envman/load.sh"

alias kswitch='kubectl config use-context'

if [ -d "/home/common/libtorch/" ]; then
    export LIBTORCH="/home/common/libtorch/"
    export LIBTORCH_INCLUDE="$LIBTORCH"
    export LIBTORCH_LIB="$LIBTORCH"
    export LD_LIBRARY_PATH=${LIBTORCH}/lib:$LD_LIBRARY_PATH
    export LIBTORCH_BYPASS_VERSION_CHECK=0
fi


if [ -d "/usr/bin/java" ]; then
    export JAVA_HOME=$(readlink -f /usr/bin/java | sed "s:bin/java::")
fi

function tmux_select()
{
    if [[ $# == 0 ]] && command tmux ls >& /dev/null; then
        command tmux attach \; choose-tree -s
    else
        command tmux new-session -s tony_desk

    fi
}
alias pgl='psql -h db.cluster.learningbymachine.com -p 9999 -U postgres'
alias pgld='psql -h db.cluster.learningbymachine.com -p 9999 -U postgres -d'
alias scyl='cqlsh 172.25.59.2 $(cat ~/.cqlcli )'
alias scyle='cqlsh 172.25.59.2 $(cat ~/.cqlcli ) -e'
